### ISSUE TITLE
The editor Hangs when switching view from default to the super-state (or vice versa).

### ISSUE THREAD

**Issue by fnunnari** [SceneMaker/VisualSceneMaker#214]
The editor hangs in the following condition/sequence:
* Define a super-state and a global variable
* In the super-state, define two states looping among them
* Run the project
* Switch to watch inside the super-state
* Editor will hang

The same happen when starting the project from inside the super-state and going back to _default_ view.

Hiding the panel showing the variable value doesn't help.

**Comment by fnunnari** [comment]
Patrick discovery:

> For me the following action (in file /src/main/java/de/dfki/vsm/editor/VarBadgeGlobal) in at line 130 " public void synchronized paintComponent(java.awt.Graphics g) {" - > "public void paintComponent(java.awt.Graphics g) {" (removing the keyword synchronized) has fixed the bug. Can you confirm this? I guess in AWT you are not supposed to mess with the thread concept, which is when you add "synchronized" ...

**Comment by fnunnari** [comment]
I had a look at the code.
Method `paintComponent()` is an override. Adding a `synchronise` to an overridden method is indeed an horror choice.
However, if the synch was there, it can be for a reason.
By a quick look, it seems that the only variable that might need protection is `mEntryList`. In fact, one can notice that it is in a synch block in some other methods.
@chiragbhuvaneshwara , can you try to narrow doen the `synch` around the for loop at line 171, which is scanning the `mEntryList`, and see if the deadlock still disappears?

**Comment by SceneMaker** [comment]
I did quite a bit of reading on if it is a good idea to synchronize the paintComponent method. Long story short: it seems not. (e.g., https://stackoverflow.com/questions/6445143/making-swing-components-synchronized). I suggest that we remove the synchronized statement from VarBadge{Local|Global}. I tested several models - no hangups. In addition, there is no need to wrap the mEntryList because it is updated (synchronized) via the update method. The paint methods only "paints" it.  BTW. There is also another update method (l. 261) that updates the mEntryList without the synchronized statement. This one shouldn't be allowed anymore. And it does not make any sense too, since it is only used by the e.dfki.vsm.util.tts.marytts.MaryTTSProcess code created by Alvaro who (i hope) has accidentally used this update method.

**Comment by chiragbhuvaneshwara** [comment]
I tried the above approach without the sync block on the paintComponent on the ReproduceEditorHang project. That solves the problem. The editor doesn't hang anymore on this project at least. Should I check anything else?

**Comment by fnunnari** [comment]
I guess you can check the synchronisation sections, e.g., at line 261 as Patrick suggested.

**Comment by fnunnari** [comment]
Closed with pull requests #221, #222, and #223.
